version: '3.7'

services:
  immo-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata-immo:/var/lib/postgresql/immo
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build:
      context: ../src
    ports:
      - "8001:8000"
    depends_on:
      - immo-postgres
    env_file:
      - api.env
    volumes:
      - ../src:/usr/src
volumes:
  pgdata-immo:
